name: Laravel CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP, with Composer and Node
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql
        tools: composer, node

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Generate key
      run: php artisan key:generate

    - name: Install NPM dependencies
      run: npm install

    - name: Update Composer dependencies
      run: composer update

    - name: Update NPM packages
      run: npm update

    - name: Run migrations
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: laravel
        DB_PORT: 3306
        DB_HOST: 127.0.0.1
        DB_USERNAME: root
        DB_PASSWORD: password
      run: php artisan migrate

    - name: Seed the database
      run: php artisan db:seed

    - name: Start Laravel server
      run: php artisan serve &
      shell: bash

    - name: Run npm development script
      run: npm run dev

    - name: Clear application cache
      run: |
        php artisan cache:clear
        php artisan route:clear
        php artisan view:clear
        php artisan config:clear
